name: Build and test
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build the api
      run: |
        cd api
        ls -la
        #eval $(minikube docker-env)
        echo "show version"
        mvn -v
        echo "cleaning"
        mvn clean package
        echo "building"
        mvn dockerfile:build
        echo "done"

    - name: build the proxy
      if: 1 == 2
      run: |
        cd ../proxy
        #eval $(minikube docker-env)
        mvn clean package
        mvn dockerfile:build

    - name: a
      if: 1 == 2
      run: |
        kubectl create -f sidecar-deploy.yml 
        kubectl expose pod api -n my-apps — type=NodePort — port 8081
        minikube service api -n my-apps

    - name: b
      run: |        
        cd $GITHUB_WORKSPACE/api
        docker build -t api .
        docker run -d -p 8080:8080 api

        # wait a bit
        sleep 10

        # call the api
        curl localhost:8080/hello
        echo "" # line break

        result=$(curl -s localhost:8080/hello)
        content=$(echo $result | jq '.content')

        if [ "$content" == "Hello World" ] ; then
          echo "Got expected result" 
        else
          echo "Did not get expected result but [$content]"  
        fi