on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build the api
      run: |
        cd api
        ls -la
        #eval $(minikube docker-env)
        echo "show version"
        mvn -v
        echo "cleaning"
        mvn clean package
        echo "building"
        mvn dockerfile:build
        echo "done"

    - name: build the proxy
      run: |
        cd ../proxy
        #eval $(minikube docker-env)
        mvn clean package
        mvn dockerfile:build

    - name: a
      if: 1 == 2
      run: |
        kubectl create -f sidecar-deploy.yml 
        kubectl expose pod api -n my-apps — type=NodePort — port 8081
        minikube service api -n my-apps

    - name: b
      run: |
        cd ../api
        docker build -t api .
        docker run -p 8080:8080 api

        curl localhost:8080/hello