name: Build and test
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build the api
      run: |
        cd api
        mvn clean package
        mvn dockerfile:build

    - name: build the docker container
      run: |        
        cd $GITHUB_WORKSPACE/api
        docker build -t api .
        docker run -d -p 8080:8080 api

        echo "Wait a bit for the container to be up"
        sleep 10

        echo "Calling the api:"
        curl localhost:8080/hello
        echo "" # line break

        result=$(curl -s localhost:8080/hello)
        content=$(echo $result | jq -r '.content')

        if [ "$content" == "Hello World" ] ; then
          echo "Got expected result :+1:" | tee $GITHUB_STEP_SUMMARY
        else
          echo ":alert: Did not get expected result but [$content]" | tee $GITHUB_STEP_SUMMARY
        fi
      
    # push the container to ghcr.io
    - name: Push the container to ghcr.io
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag api ghcr.io/${{ github.repository }}/api
        docker push ghcr.io/${{ github.repository }}/api
  
  # run the docker container with the app as a sidecar
  testing:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    needs: build
    services:
      api:
        image: api
        ports:
          - 8080:8080
    steps:
      # call the api and verify the result
      - name: Call the api
        run: |
          echo "Wait a bit for the container to be up"
          sleep 10

          echo "Calling the api:"
          curl localhost:8080/hello
          echo "" # line break

          result=$(curl -s localhost:8080/hello)
          content=$(echo $result | jq -r '.content')

          if [ "$content" == "Hello World" ] ; then
            echo "Got expected result :+1:" | tee $GITHUB_STEP_SUMMARY
          else
            echo ":alert: Did not get expected result but [$content]" | tee $GITHUB_STEP_SUMMARY
          fi
